  method /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_ENTITY.
  DATA:
    LW_ENTITY TYPE ZB3005,
    LW_ZSCWMLAGP TYPE ZSCWMLAGP.

  CLEAR:
    ER_ENTITY.

  CASE IV_ENTITY_SET_NAME.
    WHEN 'ZScwmLagpAiPostSet'.

      IO_DATA_PROVIDER->READ_ENTRY_DATA(
        IMPORTING
          ES_DATA = LW_ENTITY ).

      CLEAR LW_ZSCWMLAGP.
        LW_ZSCWMLAGP-MANDT          = '400'.
        LW_ZSCWMLAGP-LGNUM          = LW_ENTITY-LGNUM.
        LW_ZSCWMLAGP-LGPLA          = LW_ENTITY-LGPLA.
        LW_ZSCWMLAGP-LGTYP          = LW_ENTITY-LGTYP.
        LW_ZSCWMLAGP-LGBER          = LW_ENTITY-LGBER.
        LW_ZSCWMLAGP-LPTYP          = LW_ENTITY-LPTYP.

      INSERT ZSCWMLAGP FROM LW_ZSCWMLAGP.

      CALL METHOD COPY_DATA_TO_REF
        EXPORTING
          IS_DATA      = LW_ENTITY
        CHANGING
          CR_DATA      = ER_ENTITY.

    WHEN OTHERS.
  ENDCASE.
  endmethod.